import Head from 'next/head';
import { useEffect } from 'react';

import LargeListItem from '@/components/molecules/large-list-item';
import List from '@/components/atoms/list-holder';
import KeySpeakersList from '@/components/organisms/key-speakers-list';

import { fadeIn, handleScroll } from '@/scripts/animations';

import sessions from '@/data/featured-sessions.json';
import HeroImage from '@/components/organisms/hero-image/hero';

export default function Home() {
    useEffect(() => {
        // Apply fade-in effect when component mounts
        fadeIn(window);
        // Add scroll event listener and call handleScroll function
        window.addEventListener('scroll', () => handleScroll(window));
        // Remove scroll event listener when component unmounts
        return () => {
            window.removeEventListener('scroll', () => handleScroll(window));
        };
    }, []);
    return (
        <>
            <Head>
                <title>Food & Drink 2024</title>
                <meta name='description' content='Generated by create next app'/>
                <meta name='viewport' content='width=device-width, initial-scale=1'/>
                <link rel='icon' href='/favicon.ico'/>
            </Head>
            <main>
                <section>
                    <h1 class='page-heading'>Welcome to <span class='italic-text light-weight-text'>Food & Drink</span> Conference 2024!</h1>
                    <HeroImage/>
                </section>
                <section>
                    <List heading='Featured Sessions'>
                        {sessions.map((session) => (
                            <LargeListItem key={session.id} headingText={session.heading} detailText={session.time} imageSrc={session.thumbnail} />
                        ))}
                    </List>
                </section>
                <KeySpeakersList />
            </main>
        </>
    );
}
